apps/consent-ui/src/components/Footer/Versions.tsx
Updates the Footer component to use the version from consent-ui's package.json as the registry version.
=> ♻️ Use package.json's registry version in footer (#59)

apps/consent-ui/src/components/Link/LocalizedLink.tsx, apps/consent-ui/src/components/Link/utils.ts
adds a leading `/` to the `LocalizedLink` component href to fix a routing issue that (maybe?) appeared after the env var stuff got merged. TBH not sure how it was working originally!
- also fixes the prefetch link that can be seen with the browser inspector
=> fix LocalizedLink href structure

apps/consent-das/src/prismaClient.ts, apps/consent-das/src/service/create.ts, apps/consent-das/src/service/search.ts
- Added the Participant Response create/read methods
- Seed data not necessary since responses will be created with users + questions via an api call later on
Note that this branch was created from #91 due to the existing schema in that branch, so the changes are compounded from that.
=> 🗃️ Add Participant Response Prisma schema

apps/consent-api/package.json, apps/consent-api/src/routers/status.ts, apps/consent-api/tsconfig.json, apps/consent-das/src/index.ts, apps/consent-das/src/routers/swagger.ts, apps/data-mapper/src/index.ts, apps/data-mapper/src/routers/participants.ts, apps/data-mapper/src/routers/swagger.ts, apps/keys-das/src/index.ts, apps/keys-das/src/routers/ohipKeys.ts, apps/keys-das/src/routers/swagger.ts, apps/phi-das/src/routers/ohip.ts, apps/phi-das/src/routers/swagger.ts, apps/pi-das/src/index.ts, apps/pi-das/src/routers/swagger.ts, package.json, pnpm-lock.yaml
- moved `swagger-ui-express`, `swagger-jsdoc`, `@types/swagger-ui-express`, `@types/swagger-jsdoc` dependencies from `consent-api` to top level devDependencies 
- added Swagger routers for each of the DASes
=> 🚚 Add Swagger routers to all services

apps/consent-ui/src/components/Button/LinkButton.tsx
- a dumb error that I didn't catch for some reason after renaming the types of ButtonSize (not sure why it was able to build without this 🤔)
=> 🚑️ Fix renaming ButtonSize type bug

README.md, apps/consent-api/.env.schema, apps/consent-api/src/routers/consentQuestions.ts, apps/consent-das/src/routers/consentQuestions.ts, apps/consent-das/src/routers/participants.ts
- didn't pull the swagger updates to develop before merging #101 so I wasn't able to see the jsdoc lib errors for the Swagger JSDocs
- couldn't find a programmatic way to fix this other than checking where the linter is complaining and removing tabs/adding spaces, swagger-jsdocs was being annoying when I tried to just return the swagger spec yaml or json
- I guess the current approach to avoiding this error is to check the linter as you add comments (which wasn't possible when I was adding these comments in originally so this should be fine from now on)
- also added NODE_ENV to consent-api's `.env.schema` and updated the README
=> 🚨 Fix whitespace in Swagger JSDocs

apps/consent-das/prisma/migrations/20231027210340_data_model_v4_update/migration.sql, apps/consent-das/prisma/schema.prisma, apps/consent-das/prisma/seed/seed-data.ts, apps/consent-das/src/service/create.ts
Changed `consentGroup` field to be not nullable as per Data Model 4.0
- updated the Prisma schema + seed data
- updated the `create` service function
- note that the JSDocs were already listing it as required by default
=> 🗃️ Data Model v4 updates - Consent DAS

apps/consent-das/prisma/migrations/20231031195803_use_consent_question_id_enum/migration.sql, apps/consent-das/prisma/schema.prisma, apps/consent-das/prisma/seed/seed-data.ts, apps/consent-das/src/prismaClient.ts, apps/consent-das/src/routers/consentQuestions.ts, apps/consent-das/src/routers/participantResponses.ts, apps/consent-das/src/service/create.ts, apps/consent-das/src/service/search.ts, apps/consent-das/src/service/update.ts
- Added Consent Question IDs type in consent-das Prisma schema:
```
INFORMED_CONSENT__READ_AND_UNDERSTAND
RELEASE_DATA__CLINICAL_AND_GENETIC
RELEASE_DATA__DE_IDENTIFIED
RESEARCH_PARTICIPATION__FUTURE_RESEARCH
RESEARCH_PARTICIPATION__CONTACT_INFORMATION
RECONTACT__FUTURE_RESEARCH
RECONTACT__SECONDARY_CONTACT
REVIEW_SIGN__SIGNED
```
- updated ConsentQuestion.id and ParticipantResponse.consentQuestionId to use new consent question ID enum
- updated seed-data to use enum values
- updated consent-das services to use new enum values for consent question ids
- create migrations
**Note**: the routers will need to be updated after the `Zod` enum is added
=> 🗃️ Add ConsentQuestionId enum

apps/phi-das/src/routers/clinicalProfiles.ts, apps/pi-das/src/routers/clinicianInvites.ts, apps/pi-das/src/routers/participants.ts
- fixed some typos in a couple of the Swagger JSDocs `tag` fields which led to some of the router endpoints being grouped in two spots in the Swagger UI (like some under Participant and others under Participants)
=> ✏️ Fix Swagger JSDocs typos

apps/consent-das/prisma/seed/seed-data.ts, apps/consent-das/src/routers/clinicianInvites.ts, apps/consent-das/src/service/create.ts
- leftover instances of `inviteSentDate` that I didn't catch in #214
=> 🚑️ Omit inviteSentDate in Clinician Invite services

packages/types/src/entities/ClinicianInvite/ClinicianInvite.ts, packages/types/src/entities/ClinicianInvite/ConsentClinicianInvite.ts, packages/types/src/entities/ClinicianInvite/PIClinicianInvite.ts, packages/types/src/entities/ParticipantIdentification.ts
Refactor suggestions for https://github.com/OHCRN/platform/pull/235
Reworks the ClinicianInvite types file into multiple composable types.
The invite is broken in the following sections:
- `InviteClinicianFields`
- `InviteGuardianFields`
- `InviteParticipantFields`
- `InviteEntity`
Which are then composed as:
- `ClinicianInviteRequest` = (`InviteClinicianFields` & `InviteGuardianFields` & `InviteParticipantFields`) + guardian refinement
- `ClinicianInviteResponse` = `InviteEntity` & `ClinicianInviteRequest`
A couple entities used in DAS requests were also reworked to use these components:
- `ConsentClinicianInviteRequest` = `{id}` & `InviteClinicianFields`
- `PIClinicianInviteRequest` = `InviteParticipantFields` & `InviteGuardianFields`
=> PR Feedback - Suggestion for re-organizing Clinician Invite types

apps/consent-api/src/routers/invites.ts, apps/data-mapper/src/services/das/pi.ts, apps/pi-das/package.json, apps/pi-das/src/routers/clinicianInvites.ts, apps/pi-das/src/routers/swagger.ts, apps/pi-das/src/service/create.ts, pnpm-lock.yaml
Implemented complete error handling, validation, and logging for the `POST /invites` router and `createClinicianInvite` service in PI DAS using `consent-api` as an example.
- Added `express-request-validation` from shared packages to use `withRequestValidation` to validate the endpoint's request body
- Updated the endpoint's HTTP Responses to use the appropriate `ErrorResponse`
- Added a 400 RequestValidationError and 409 ConflictError to the endpoint responses, updated the JSDocs
- Updated the return type of the `createClinicianInvite` service to `Result` so it returns appropriate `Success` and `Failure` responses to the router
- Updated the Prisma create request so it returns a failure response if an error occurred
>**Note:** The parameter type for `createClinicianInvite` was changed to …
=> 🦺 PI DAS error handling for Clinician Invite flow (#275)

apps/consent-das/package.json, apps/consent-das/src/routers/clinicianInvites.ts, apps/consent-das/src/routers/swagger.ts, apps/consent-das/src/service/create.ts, apps/data-mapper/src/services/das/consent.ts, apps/pi-das/src/service/create.ts, pnpm-lock.yaml
Implemented complete error handling, validation, and logging for the `POST /invites` router and `createClinicianInvite` service in Consent DAS using `consent-api` and `pi-das` as an example.
- Added `express-request-validation` from shared packages to use `withRequestValidation` to validate the endpoint's request body
- Updated the endpoint's HTTP Responses to use the appropriate `ErrorResponse`
- Added a 400 RequestValidationError and 409 ConflictError to the endpoint responses, updated the JSDocs
- Updated the return type of the `createClinicianInvite` service to `Result` so it returns appropriate `Success` and `Failure` responses to the router
- Updated the Prisma create request so it returns a failure response if an error occurred
>**Note:** The endpoint request body validation was …
=> 🦺 Consent DAS error handling for Clinician Invite flow (#275)

apps/consent-api/src/routers/invites.ts, apps/consent-api/src/routers/steps/informedConsent.ts, apps/consent-das/src/routers/clinicianInvites.ts, apps/consent-das/src/routers/consentQuestions.ts, apps/consent-das/src/routers/participantResponses.ts, apps/data-mapper/src/routers/invites.ts, apps/data-mapper/src/routers/steps/informedConsent.ts, apps/pi-das/src/routers/clinicianInvites.ts, packages/types/src/httpResponses/NotFoundErrorResponse.ts, packages/types/src/httpResponses/ServerErrorResponse.ts, packages/types/src/httpResponses/index.ts
Abstracts all `500 ServerError` responses we return in our routers to a `ServerErrorResponse` and updates all the routers to use it.
=> 🎨 #321: Add ServerErrorResponse type

apps/consent-api/src/routers/invites.ts, apps/consent-api/tests/README.md, apps/consent-api/tests/config.ts, docs/shared-types.md, packages/types/src/entities/ClinicianInvite/PIClinicianInvite.ts, packages/types/src/entities/ParticipantIdentification.ts
Updated the shared types docs after the refactoring of the `ClinicianInvite` schemas. Also updated the README in the routers unit test directory to include how we mock the app config and environment vars. Caught a few formatting bugs while looking through these files too and fixed them!
=> 📝 Update router testing and shared types docs

apps/consent-ui/src/components/common/Header/HelpButton.module.scss
Fixes header button height in Safari, see ticket for the screenshot
- [ x Builds locally without errors or warnings
=> 🐛#396: Fix Help button height in Safari

apps/consent-ui/src/components/views/ConsentWizard/InformedConsent/index.tsx
- change __blank to _blank on a link in the informed consent page
=> ✏️  change __blank to _blank

Dockerfile
Makes assets in the `/public` directory of Consent UI available when running built Docker images.
* Copy `/public` directory to make public assets available in built Docker images of Consent UI
=> 🐛 Fix Static Assets in Consent UI Docker Images

apps/consent-ui/src/components/views/Invite/ClinicianInviteForm/index.tsx, packages/types/src/common/String.ts, packages/types/src/common/regexes.ts, packages/types/src/entities/ClinicianInvite.ts, packages/types/src/entities/fields/Name.ts, packages/types/src/services/consentApi/requests/ClinicianInvite.ts, packages/types/src/services/consentApi/responses/ClinicianInvite.ts, packages/types/src/services/dataMapper/requests/ClinicianInvite.ts, packages/types/src/services/dataMapper/responses/ClinicianInvite.ts, packages/types/tests/entities/ClinicianInvite.spec.ts, packages/types/tests/entities/Name.spec.ts
Suggestions for https://github.com/OHCRN/platform/pull/431. Not exhaustively tested in the UI form, so please verify this matches the intended behaviour!
- Adds `EmptyOrOptionalName` as the field type for `participantPreferredName` on the invite form to pass validation if the field is an empty string
- adds convenience String types for trimmed and optional strings that can be chained with `z.regex()`. Also adds literal empty string and whitespace types
- adds 'OptionalName` and `EmptyOrOptionalName` types
- updates `Name` test with cases for `EmptyOrOptionalName` type. Tests for `Name` and `OptionalName` need to be implemented
- updates `ClinicianInvite` test to use `ClinicianInviteRequest` schema instead of `ClinicianInviteResponse` schema
Before running these changes, you will need to …
=> 285 - 🏷️ Regex types suggested changes

packages/types/src/services/dataMapper/requests/ClinicianInvite.ts
- change absolute import to a relative one in ClinicianInvite.ts, to resolve an error in the `pnpm run dev` process.
=> ✏️ typo: fix import in ClinicianInvite

apps/consent-ui/src/components/common/Modal/index.tsx
- change how ReactModal finds root element, because server components don't have access to the window/document object
- the error was being thrown in the terminal not the browser console, because it's a server component
=> 🐛 bugfix: change how ReactModal finds root element

apps/consent-ui/src/i18n/locales/fr/consentResearchParticipationForm.ts
No ticket - just noticed when reviewing another pr
Fixes an incorrect import for the `yes`/`no` form label in step 3 of the wizard
=> fix incorrect dictionary import

apps/phi-das/prisma/migrations/20240307194322_data_model_v5_update/migration.sql, apps/phi-das/prisma/schema.prisma, apps/pi-das/prisma/migrations/20240307194410_data_model_v5_update/migration.sql, apps/pi-das/prisma/schema.prisma
Add missing fields for data model v5.0
PI DAS
- Participant table
- assentFormIdentifier (optional, string)
- hasOhip (required, boolean, default true) (ALREADY ADDED IN ANOTHER PR)
- Clinician Invites table
- assentFormIdentifier (optional, string)
PHI DAS
- Clinical Profile table
- vitalStatus
Before running these changes, you will need run migrations
```
pnpm prisma:generate
```
=> 🗃️#458: Add missing fields for data model v5.0

apps/consent-ui/src/components/providers/AppConfigContextProvider/index.tsx, apps/consent-ui/src/components/views/Dashboard/TempPdfButtons.tsx, apps/consent-ui/src/components/views/Dashboard/TempPdfButtonsWrapper.tsx, apps/consent-ui/src/components/views/Dashboard/generateConsentPdf/mockData.ts, apps/consent-ui/src/components/views/Dashboard/index.tsx, apps/consent-ui/src/config/appConfig.ts, apps/consent-ui/src/config/clientConfig.ts, apps/consent-ui/src/config/types.ts
Enforces server-only usage of app config functions. Also contains a small refactor of the temporary PDF buttons preventing the app config function from getting called client-side.
* Refactors `appConfig.ts` and `clientConfig.ts` to support `server-only` usage, splitting type definitions out into separate `types.ts` in `src/config/`
* Adds import for `server-only` package on `appConfig.ts` and `clientConfig.ts`
* Adds an intermediate `TempPDFButtonsWrapper` server component to fetch env vars
* Removes temporary PDF button logic from `Dashboard` and into `TempPDFButtonsWrapper` for easy disposal later 🙏
=> 🔧 Enforce server-only Usage for App Config and Client App Config

packages/types/src/entities/Register.ts, packages/types/src/entities/index.ts, packages/types/src/services/consentUi/requests/Register.ts, packages/types/src/services/consentUi/utils/guardianFields.ts, packages/types/tests/services/participantRegistrationRefinements.spec.ts
Creates a Register base type file for the consentUi Register request schema to import from, to fix some circular imports.
=> ♻️ 476 - create Register base type
